name: Build and push
on:
  push:
    branches:
      - main
    paths:
      - .drone-latest-version.txt
      - .github/workflows/*
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine tag
        id: tag
        run: |
          CONTENT=$(cat .drone-latest-version.txt)
          echo "::set-output name=DRONE_VERSION::$CONTENT"

      - name: Output tag
        run: |
          echo "DRONE_VERSION: ${{ steps.tag.outputs.DRONE_VERSION }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/drone:latest, ${{ secrets.DOCKERHUB_USERNAME }}/drone:${{ steps.tag.outputs.DRONE_VERSION }}
          build-args: |
            DRONE_VERSION=${{ steps.tag.outputs.DRONE_VERSION }}
