name: Get latest release version
on:
  schedule:
    - cron: "1 10 * * *"

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/harness/drone/releases/latest | \
          jq -r ".tag_name" > .drone-latest-version.txt

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")

      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'dec0dOS bot'
          git config --global user.email 'dec0dos@users.noreply.github.com'
          git commit -am "ci: new drone release version"
          git push
